# Camera 1 - Top Left USB Port — by-path symlink to keep it stable
video_device /dev/v4l/by-path/platform-xhci-hcd.1-usb-0:1:1.0-video-index0

width 1280
height 1024
framerate 15

# MJPEG
v4l2_palette 8

text_left MICROSCOPE
text_right %d-%m-%Y\n%T-%q
text_scale 2

stream_port 8085
stream_localhost off

picture_output off
movie_output off
