# Camera 2 - Bottom Left USB Port  — by-path symlink to keep it stable
video_device /dev/v4l/by-path/platform-xhci-hcd.0-usb-0:1:1.0-video-index0 

width 640
height 480
framerate 15
v4l2_palette 17        # YUYV compression format
#v4l2_palette 8        # MJPG / MJPEG compression format

# Overlay text (optional)
text_left CAM2
text_right %d-%m-%Y\n%T-%q
text_scale 2

# Stream settings for this camera
stream_port 8082
stream_localhost off

# No file outputs
picture_output off
movie_output off
