# Camera 3 - Top Right USB Port — by-path symlink to keep it stable
video_device /dev/v4l/by-path/platform-xhci-hcd.0-usb-0:2:1.0-video-index0

width 640
height 480
framerate 15
v4l2_palette 17        # YUYV compression format
#v4l2_palette 8        # MJPG / MJPEG compression format

# Overlay text (optional)
text_left CAM3
text_right %d-%m-%Y\n%T-%q
text_scale 1

# Stream settings for this camera
stream_port 8083
stream_localhost off

# No file outputs
picture_output off
movie_output off
